apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cms-docs.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cms-docs.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cms-docs.name" . }}
    spec:
      containers:
        - name: cloudmasa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "development"
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              mkdir -p /app
              cp -rL /source/. /app/
              cd /app
                # Verify critical file exists
              if [ ! -f "src/css/custom.css" ]; then
                echo "ERROR: src/css/custom.css is missing!" >&2
                exit 1
              fi
              
              npm install
              npm start
          volumeMounts:
            - name: cloudmasa-source
              mountPath: /source
              readOnly: true
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      volumes:
        - name: cloudmasa-source
          configMap:
            name: {{ include "cms-docs.fullname" . }}-docusaurus-source
      restartPolicy: Always
