{{- if .Values.query.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-query
  namespace: {{ .Release.Namespace }}
  labels:
    component: query
    {{- include "thanos.labels" . | nindent 4 }}
    
spec:
  replicas: {{ .Values.query.replicas }}
  selector:
    component: {{ $component }}
    matchLabels:
      {{- include "thanos.selectorLabels" . | nindent 6 }}
      component: query
  template:
    metadata:
      labels:
        {{- include "thanos.selectorLabels" . | nindent 8 }}
      annotations: {}
    spec:
      serviceAccountName: {{ include "thanos.serviceAccountName" . }}
      containers:
      - name: query
        image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args:
          - query
          {{- range .Values.query.stores }}
          - --store={{ . }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.query.ports.http | default 10902 }}
          name: http
        - containerPort: {{ .Values.query.ports.grpc | default 10901 }}
          name: grpc
        resources:
          {{- toYaml .Values.query.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /-/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
