{{- if .Values.compactor.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thanos.fullname" . }}-compactor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    app.kubernetes.io/component: compactor
spec:
  replicas: {{ .Values.compactor.replicas }}
  selector:
    matchLabels:
      {{- include "thanos.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: compactor
  template:
    metadata:
      labels:
        {{- include "thanos.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: compactor
    spec:
      serviceAccountName: {{ include "thanos.serviceAccountName" . }}
      containers:
        - name: compactor
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          args:
            - compact
             - --wait
            - --data-dir=/var/thanos/compact
            - --objstore.config-file=/etc/thanos/objstore.yml
            - --http-address=0.0.0.0:10902
            - --retention.resolution-raw={{ .Values.compactor.retentionResolutionRaw }}
            - --retention.resolution-5m={{ .Values.compactor.retentionResolution5m }}
            - --retention.resolution-1h={{ .Values.compactor.retentionResolution1h }}
          volumeMounts:
            - name: objstore-config
              mountPath: /etc/thanos
              readOnly: true
            - name: compact-data
              mountPath: /var/thanos/compact
          ports:
            - containerPort: 10902
              name: http
          resources:
            {{- toYaml .Values.compactor.resources | nindent 12 }}
      volumes:
        - name: objstore-config
          secret:
            secretName: {{ .Values.objstoreConfig.secret.name }}
        - name: compact-data
          emptyDir: {}
{{- end }}
